name: krushapp
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.1+1001

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_responsive_screen: ^1.0.0
  country_code_picker: ^1.2.4
  pin_code_fields: ^2.3.0+3
  #fluttertoast: ^3.1.3
  progress_dialog: ^1.2.2
  fluttertoast: ^4.0.1
  shared_preferences: ^0.5.8
  http: any
  sticky_headers: ^0.1.8+1
  overlay_support: ^1.0.5
  emoji_picker: ^0.1.0
  flutter_keyboard_visibility: ^3.2.1
  flutter_staggered_animations: ^0.1.2
  flutter_svg: ^0.18.1
  #Firebase dep
  firebase_core: ^0.4.2+1
  firebase_messaging: ^6.0.16
  flutter_ringtone_player: ^2.0.0
  assets_audio_player: ^2.0.10
  #sound_mode: ^0.2.0
  vibration: ^1.7.0
  #  cloud_firestore: ^0.13.4+1
  #  collection: ^1.14.11
  image_picker: ^0.6.6+5
  intl: ^0.16.1
  progress_indicators: ^0.1.5
  webview_flutter: ^0.3.22+1
  share: ^0.6.5+4
  laravel_echo: ^0.2.2
  flutter_pusher_client: ^0.3.1
  contacts_service: ^0.4.6
  image: ^2.1.14
  path_provider: ^1.6.14
  gallery_saver: ^2.0.1
  permission_handler: ^5.0.1+1
  giphy_picker: ^1.0.6

  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  get_it: ^4.0.2
  flutter_bloc: ^6.0.5
  flutter_local_notifications: ^1.4.4+1
  velocity_x: ^0.4.1
  device_info: ^0.4.2+4
  cached_network_image: ^2.2.0+1
  image_cropper: ^1.2.3
  amazon_cognito_identity_dart: ^0.0.22
  flutter_country_picker: ^0.1.6
  stripe_payment: ^1.0.7
  auto_size_text: ^2.1.0
  firebase_admob: ^0.9.3+4
  # awesome_dialog: ^1.1.3
  firebase_remote_config: ^0.3.1+1
  package_info: ^0.4.1
  firebase_auth: ^0.16.1
  firebase_database :

  url_launcher: ^5.5.0
  equatable: ^1.2.4
  in_app_purchase: ^0.3.4+5
  google_fonts: ^1.1.0
  dio: ^3.0.10
  admob_flutter: ^1.0.0
  flutter_sticky_header: ^0.5.0    
  analyzer: ^0.40.4
  rflutter_alert: ^1.1.0
  purchases_flutter: ^1.4.1
  app_settings: ^4.0.4

  in_app_review: ^1.0.2

  store_redirect: ^1.0.2
  flutter_secure_storage: ^3.3.5
  photo_view: ^0.10.3

  storage_path: ^0.0.8
  transparent_image: any
  path_provider_ex: ^1.0.1
  flutter_file_manager: ^0.2.0
  thumbnails: ^1.0.1
  flutter_video_info: ^1.1.0
  bubble_tab_indicator: ^0.1.4
  
  # webview_flutter: ^0.3.22+1

# dependency_overrides:
#   dartx: ^0.3.0
dependency_overrides:
  dartx: ^0.5.0

dev_dependencies:
  # flutter_launcher_icons: ^0.7.5
  flutter_test:
    sdk: flutter

  hive_generator: 
  build_runner: 

# flutter_icons:
#   android: true
#   ios: true
#   image_path: "assets/images/KrushAppIconFilled.png"
# adaptive_icon_background: "#ffffff"
# adaptive_icon_foreground: "assets/images/KrushAppIcon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/icons/
    - assets/icons/
    - assets/images/
    - assets/svg/
    - assets/sounds/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/ProductSans-Thin.ttf
          weight: 200
        - asset: assets/fonts/ProductSans-Light.ttf
          weight: 300
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/ProductSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/ProductSans-Bold.ttf
          weight: 600
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 700
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 800
        - asset: assets/fonts/ProductSans-Black.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
